apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://kubereboot.github.io/charts
    name: kured
    releaseName: kured
    version: 5.11.0
    valuesFile: values.yaml
    namespace: platform-kured

resources:
  - prometheus-rule.yaml
  - secrets.yaml
