apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-cm.yaml
  - database.yaml
  - deployment.yaml
  - httproute-dmz.yaml
  - ingress.yaml
  - namespace.yaml
  - secrets.yaml
