apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    releaseName: external-secrets
    version: 2.0.0
    valuesFile: values.yaml
    namespace: external-secrets

resources:
  - base/bitwarden-certificates.yaml
  - base/secret-store.yaml
