apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://stakater.github.io/stakater-charts
    name: reloader
    releaseName: reloader
    version: 2.2.4
    namespace: reloader
