apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-webhook.yaml
  - secrets.yaml

helmCharts:
  - repo: https://zapier.github.io/kubechecks
    name: kubechecks
    releaseName: kubechecks
    version: v3.0.0
    valuesFile: values.yaml
    namespace: platform-kubechecks

# NOTE: Workaround since the helm chart uses the "latest" tag.
images:
  - name: ghcr.io/zapier/kubechecks
    newTag: v3.0.0-rc1
