configMap:
  create: true
  env:
    KUBECHECKS_ARGOCD_API_NAMESPACE: argocd
    KUBECHECKS_ARGOCD_API_PLAINTEXT: true
    KUBECHECKS_ARGOCD_API_SERVER_ADDR: argocd-server.argocd.svc.cluster.local
    # KUBECHECKS_ARGOCD_REPOSITORY_ENDPOINT:
    KUBECHECKS_ENSURE_WEBHOOKS: true
    KUBECHECKS_LABEL_FILTER: allowed # kubechecks:allowed
    KUBECHECKS_VCS_TYPE: github
    KUBECHECKS_WEBHOOK_URL_BASE: https://webhooks.sbling.net
    KUBECHECKS_WEBHOOK_URL_PREFIX: /kubechecks/webhook

deployment:
  envFrom:
    - secretRef:
        name: kubechecks-secrets

  image:
    pullPolicy: IfNotPresent
