apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-datasource.yaml

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: loki
    releaseName: loki
    version: 6.53.0
    valuesFile: values.yaml
    namespace: platform-monitoring-loki
