apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-monitoring-grafana

resources:
  - https://github.com/grafana/grafana-operator/releases/download/v5.21.4/kustomize-cluster_scoped.yaml
  - dashboards
  - grafana.yaml

patches:
  - patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
        name: grafanas.grafana.integreatly.org
