apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - push-secret.yaml

patches:
  - path: argocd-cm.yaml

configMapGenerator:
  - name: argocd-bootstrap-script
    files:
      - bootstrap.sh
