name: Build OCI Images

on:
  pull_request:
    paths: &paths
      - .github/workflows/build-images.yaml
      - "images/**"
  push:
    paths: *paths
    branches:
      - master

jobs:
  detect-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed.outputs.all_changed_files }}
      any_changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect changed images
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files: "images/**"
          dir_names: "true"
          dir_names_max_depth: "2"
          matrix: "true"

  build:
    needs: detect-images
    if: needs.detect-images.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.detect-images.outputs.matrix) }}
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Get image name
        id: image-name
        run: echo "value=$(basename '${{ matrix.directory }}')" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ steps.image-name.outputs.value }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDDTHHmmss'}},enable={{is_default_branch}}
            type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.directory }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ steps.image-name.outputs.value }}
          cache-to: type=gha,scope=${{ steps.image-name.outputs.value }},mode=max
